# Generated by Django 4.1 on 2022-10-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobclient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='deleting',
            field=models.BooleanField(default=False),
        ),
    ]
